### ISSUE TITLE
Socrata Publication is failing with `illegal field name` error.

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-publishing#257]
Originally reported by Kenny M., the `cameras_socrata` publisher is failing with a `502` error. Investigation needed.

Updated title to reflect impact across datasets.

**Comment by johnclary** [comment]
Updater. Many of our socrata publication scripts have been failing since 9/30. Details in my ticket to Socrata:

> Hello,
> 
> On 9/30 we started receiving a 400 error on our API requests: "Illegal field name sent".
> 
> It's happening with many datatsets, because historically the API ignored unrecognized field names.
> 
> Can you confirm if/when there was an API change? What other changes do we need to be aware of?
> 
> So you have a concrete example, our upload to dataset p53x-x73x is now failing with this message:
> 
> {
> "code" : "invalid_request",
> "error" : true,
> "message" : "Illegal field name sent: switch_comm"
> }
> 
> I understand the error; just need clarification on if/when API changes were made.
> 
> Thanks.
> John

**Comment by johnclary** [comment]
From Palmer:

> It does look like a subset of datasets were upgraded (see [this article](https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.socrata.com%2Fhc%2Fen-us%2Farticles%2F360018865074-Technical-Update-Dataset-Storage-Upgrade&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C94d7142cba004717673908d7483a8103%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637057288417941724&sdata=Hb1I7gN67t5wKfwpzZuLjAkqD1kfJeke9QIhUNo8EeY%3D&reserved=0) for more information) at the end of September, which is almost certainly what is causing this change in behavior.

**Comment by johnclary** [comment]
The field name validation was not communicated as part of the API updates. I asked Palmer to rollback the changes until we can address the issue.

> Thank you, Palmer, for that info. I don't see mention of the illegal field name validation. Am I missing it here? https://support.socrata.com/hc/en-us/articles/360024040594-Dataset-Validation-for-Column-Data-Type-Values
>
> I am wondering if it's possible to request a rollback of our affected datasets, to give a bit of lead time to handle this. It's broken a number of our critical ETL processes.

**Comment by johnclary** [comment]
Socrata rolled back the API changes to our datasets. We have bought some time to address this but will jump on it ASAP. Leaving in sprint 9 for now.

**Comment by johnclary** [comment]
`socratautil` has been patched is running successfully. Waiting for confirmation from Socrata that they have re-applied the new API validations.

**Comment by amenity** [comment]
@johnclary - any word from Socrata?

**Comment by johnclary** [comment]
No, but this is ok to close. Closing.
