### ISSUE TITLE
Radar Count Publisher is Failing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-publishing#266]
It's failing at [this line](https://github.com/cityofaustin/atd-data-publishing/blob/173b5510289508251f7f73da366c07c7b6db598a/transportation-data-publishing/open_data/radar_count_pub.py#L1590) with the error: `'<' not supported between instances of 'str' and 'int'`.

Appears to be related to Socrata API changes.

**Comment by amenity** [comment]
@johnclary - looks like you just need @sergiogcx to review [the PR](https://github.com/cityofaustin/atd-data-publishing/pull/268)...Then merge to master and close this dude?

**Comment by amenity** [comment]
@johnclary ping 🛎
